### ISSUE TITLE
Can not upload an image, try another

### ISSUE THREAD

**Issue by HitArrowLegend** [FlusherDock1/EditorJS#17]
**Describe the bug**
Pretty sure there is an easy fix but I'm lost in all those files. When I try to upload an image, it says "Can not upload an image, try another". At this point, I've tried all the images on my desktop but none worked.

**To Reproduce**
1. Upload an image using the image tool
2. See error

**Screenshots**
https://puu.sh/HbHWH/69d7b1bb93.png

**Comment by Donokami** [comment]
Same issue there!

**Comment by LeMaX10** [comment]
Hello!
This bug fixed in https://github.com/FlusherDock1/EditorJS/pull/15. 

Awaiting the merger.

**Comment by FlusherDock1** [comment]
Fixed

**Comment by HitArrowLegend** [comment]
Still having the same issues after the update : Can not upload an image, try another.

I'm using the latest version 1.7.3

**Comment by LeMaX10** [comment]
> Still having the same issues after the update : Can not upload an image, try another.
> 
> I'm using the latest version 1.7.3

Hello!
Please tell me:
1. Are there any restrictions on the size of the uploaded file?
2. Is the address in the config/app.php url equivalent to the address specified in the browser?

**Comment by HitArrowLegend** [comment]
do you mean that ? 

 /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
    */

    'url' => 'http://localhost',

Should I input my website url there ?

**Comment by LeMaX10** [comment]
> Should I input my website url there ?
> 
> Edit: It works. don't mind me :/

Good day!

Yes, one of the security policies, namely "Turn off blocking of external requests to EditorJS plugins", requires the exact site address to be in this configuration, this is necessary to avoid possible automatic requests from third-party sites.
